[workspace]
members = [
    "battle_server",
    "playground",
    "data_grabbing",
    "burn_ai_model",
    "training",
]
resolver = "3"


[workspace.dependencies]
burn = "~0.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
burn_ai_model = { path = "./burn_ai_model" }
